const assert=require('node:assert/strict');
const api=require('../live-demos/assets/js/netherlands-products.js');
assert.equal(api.offsetMinutes('2026-01-15'),60);
assert.equal(api.offsetMinutes('2026-07-15'),120);
assert.equal(api.offsetMinutes('2026-10-24'),120);
assert.equal(api.offsetMinutes('2026-10-26'),60);
const site=api.sites.find(x=>x.id==='copernicus');
assert.equal(api.solarMinutes('2026-06-21',site.lat,site.lon,-18),null);
const winterSunset=api.solarMinutes('2026-12-21',52.366,4.917,-.833);
assert(winterSunset>16*60&&winterSunset<17*60,'Amsterdam winter sunset should be around 16:30 local');
const summerSunset=api.solarMinutes('2026-06-21',52.366,4.917,-.833);
assert(summerSunset>21*60&&summerSunset<22*60+30,'Amsterdam summer sunset should be around 22:00 local');
const winterDark=api.solarMinutes('2026-12-21',site.lat,site.lon,-18);assert(winterDark>winterSunset);
const input={date:'2026-06-21',target:'deep',access:true,returnPlan:true,weather:true,warning:'clear'};
assert.equal(api.skyDecision(site,input).status,'CHANGE PRODUCT');
assert.equal(api.skyDecision(api.sites.find(x=>x.id==='kennemerland'),input).status,'BLOCKED');
assert.equal(api.skyDecision(site,{...input,access:false}).status,'HOLD');
assert.equal(api.skyDecision(site,{...input,warning:'unsafe'}).status,'BLOCKED');
assert.equal(api.skyDecision(site,{...input,weather:false}).status,'HOLD');
assert.equal(api.skyDecision(site,{...input,date:'2026-12-21'}).status,'REVIEW READY');
assert.equal(api.skyDecision(api.sites[0],{...input,target:'moon',weather:false}).status,'REVIEW READY');
assert.equal(api.dispatchDecision({pax:20,capacity:19,access:true,team:true}).status,'BLOCKED');
assert.equal(api.dispatchDecision({pax:19,capacity:19,access:false,team:true}).status,'HOLD');
assert.equal(api.dispatchDecision({pax:19,capacity:19,access:true,team:true}).status,'REVIEW READY');
assert.equal(Object.keys(api.routes).length,3);
assert.equal(api.time(null),'Does not occur on this date');
assert.equal(api.time(1450),'00:10 (+1 day)');
console.log('Dutch clocks, seasonal darkness, access/weather holds and passenger-capacity gates passed.');
