"""Bundle InfraQuote CSS in its original cascade order, resolving imports once."""
import argparse
import json
from pathlib import Path
import re
ROOT = Path(__file__).resolve().parents[1]

def build(check=False):
    seen = set()
    def expand(path):
        if path in seen:
            return ''
        seen.add(path)
        text = (ROOT / path).read_text()
        def imported(match):
            url = match.group(1).split('?')[0]
            target = url.lstrip('/') if url.startswith('/') else (Path(path).parent / url).as_posix()
            return expand(target)
        text = re.sub(r'@import\s+url\(["\']([^"\']+)["\']\)\s*;', imported, text)
        return '\n/* Source: ' + path + ' */\n' + text
    content = '/* Generated by scripts/build_infraquote_styles.py. Edit source files, then rebuild. */\n'
    content += ''.join(expand(path) for path in json.loads((ROOT / 'content/infraquote-styles.json').read_text()))
    target = ROOT / 'assets/css/infraquote-bundle.css'
    if check:
        if not target.exists() or target.read_text() != content:
            raise SystemExit('InfraQuote stylesheet bundle needs rebuilding.')
    else:
        target.write_text(content)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    build(parser.parse_args().check)
